name: Build Python wheels

on: [push, pull_request]

jobs:
  build_python_wheels:
    name: Build Python wheels on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4

      - name: Build Python wheels
        uses: pypa/cibuildwheel@v3.1.2
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.13
